sudo: required

language: typescript

services:
  - docker

script:
  - docker build -t gretro/robs-fetch .
  - docker run --name robs-fetch-build gretro/robs-fetch
  - ./deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always